USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'STAR')
BEGIN
    ALTER DATABASE STAR SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE STAR;
END
GO

CREATE DATABASE STAR;
GO

PRINT 'Database STAR created successfully.';
GO
