USE DV;
GO

IF OBJECT_ID('Sat_Sales', 'U') IS NOT NULL DROP TABLE Sat_Sales;
IF OBJECT_ID('Sat_Product', 'U') IS NOT NULL DROP TABLE Sat_Product;
IF OBJECT_ID('Sat_Customer', 'U') IS NOT NULL DROP TABLE Sat_Customer;
IF OBJECT_ID('Link_Sales', 'U') IS NOT NULL DROP TABLE Link_Sales;
IF OBJECT_ID('Hub_Sales', 'U') IS NOT NULL DROP TABLE Hub_Sales;
IF OBJECT_ID('Hub_Product', 'U') IS NOT NULL DROP TABLE Hub_Product;
IF OBJECT_ID('Hub_Customer', 'U') IS NOT NULL DROP TABLE Hub_Customer;
GO

CREATE TABLE Hub_Customer (
    Customer_HK BINARY(16) NOT NULL,
    CustomerID INT NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    LOAD_END_DTS DATETIME,
    RECORD_SOURCE NVARCHAR(100),
    CONSTRAINT PK_Hub_Customer PRIMARY KEY (Customer_HK)
);
GO

CREATE TABLE Hub_Product (
    Product_HK BINARY(16) NOT NULL,
    ProductID INT NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    LOAD_END_DTS DATETIME,
    RECORD_SOURCE NVARCHAR(100),
    CONSTRAINT PK_Hub_Product PRIMARY KEY (Product_HK)
);
GO

CREATE TABLE Hub_Sales (
    Sales_HK BINARY(16) NOT NULL,
    SalesID INT NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    LOAD_END_DTS DATETIME,
    RECORD_SOURCE NVARCHAR(100),
    CONSTRAINT PK_Hub_Sales PRIMARY KEY (Sales_HK)
);
GO

CREATE TABLE Link_Sales (
    Link_Sales_HK BINARY(16) NOT NULL,
    Sales_HK BINARY(16) NOT NULL,
    Customer_HK BINARY(16) NOT NULL,
    Product_HK BINARY(16) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    LOAD_END_DTS DATETIME,
    RECORD_SOURCE NVARCHAR(100),
    CONSTRAINT PK_Link_Sales PRIMARY KEY (Link_Sales_HK)
);
GO

CREATE TABLE Sat_Customer (
    Customer_HK BINARY(16) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    LOAD_END_DTS DATETIME,
    CustomerName NVARCHAR(100),
    CustomerBirth DATE,
    CustomerAddr NVARCHAR(200),
    RECORD_SOURCE NVARCHAR(100),
    HASH_DIFF BINARY(16),
    CONSTRAINT PK_Sat_Customer PRIMARY KEY (Customer_HK, LOAD_DTS)
);
GO

CREATE TABLE Sat_Product (
    Product_HK BINARY(16) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    LOAD_END_DTS DATETIME,
    ProductName NVARCHAR(100),
    ProductCode NVARCHAR(50),
    RECORD_SOURCE NVARCHAR(100),
    HASH_DIFF BINARY(16),
    CONSTRAINT PK_Sat_Product PRIMARY KEY (Product_HK, LOAD_DTS)
);
GO

CREATE TABLE Sat_Sales (
    Sales_HK BINARY(16) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    LOAD_END_DTS DATETIME,
    SalesNumber NVARCHAR(50),
    SalesAmount DECIMAL(18, 2),
    RECORD_SOURCE NVARCHAR(100),
    HASH_DIFF BINARY(16),
    CONSTRAINT PK_Sat_Sales PRIMARY KEY (Sales_HK, LOAD_DTS)
);
GO

PRINT 'Data Vault tables created successfully.';
GO
