USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'STAGE')
BEGIN
    ALTER DATABASE STAGE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE STAGE;
END
GO

CREATE DATABASE STAGE;
GO

PRINT 'Database STAGE created successfully.';
GO
