USE STAGE;
GO

IF OBJECT_ID('STG_Sales', 'U') IS NOT NULL DROP TABLE STG_Sales;
IF OBJECT_ID('STG_Customer', 'U') IS NOT NULL DROP TABLE STG_Customer;
IF OBJECT_ID('STG_Product', 'U') IS NOT NULL DROP TABLE STG_Product;
GO

CREATE TABLE STG_Customer (
    CustomerID INT,
    CustomerName NVARCHAR(100),
    CustomerBirth DATE,
    CustomerAddr NVARCHAR(200),
    LOAD_DTS DATETIME DEFAULT GETDATE(),
    LOAD_END_DTS DATETIME,
    RECORD_SOURCE NVARCHAR(100) DEFAULT 'OLShop',
    HK BINARY(16),
    HASH_DIFF BINARY(16)
);
GO

CREATE TABLE STG_Product (
    ProductID INT,
    ProductName NVARCHAR(100),
    ProductCode NVARCHAR(50),
    LOAD_DTS DATETIME DEFAULT GETDATE(),
    LOAD_END_DTS DATETIME,
    RECORD_SOURCE NVARCHAR(100) DEFAULT 'OLShop',
    HK BINARY(16),
    HASH_DIFF BINARY(16)
);
GO

CREATE TABLE STG_Sales (
    SalesID INT,
    SalesNumber NVARCHAR(50),
    CustomerID INT,
    ProductID INT,
    SalesAmount DECIMAL(18, 2),
    LOAD_DTS DATETIME DEFAULT GETDATE(),
    LOAD_END_DTS DATETIME,
    RECORD_SOURCE NVARCHAR(100) DEFAULT 'OLShop',
    HK BINARY(16),
    HASH_DIFF BINARY(16)
);
GO

PRINT 'Tables created successfully in STAGE.';
GO
